### ISSUE TITLE
CrowdStrikeURLProvider processor failing to download Crowdstrike Falcon

### ISSUE THREAD

**Issue by K3ll3r** [autopkg/MLBZ521-recipes#62]
I'm trying to use the CrowdStrikeFalcon recipe to pull the latest version of the Falcon sensor via the API. The authorization seems to work fine, and I'm able to generate an access token and find a matching build, but the curl fails and I get the error "Something went wrong assigning environment variables!"

Anyone else run into this?

```
CrowdStrikeURLProvider
{'Input': {'api_region_url': 'https://api.crowdstrike.com',
           'client_id': 'redacted',
           'client_secret': 'redacted',
           'policy_id': 'redacted'}}
CrowdStrikeURLProvider: Access Token:  {redacted}
CrowdStrikeURLProvider: Build version for matching Policy:  {redacted}
Traceback (most recent call last):
  File "~/Library/AutoPkg/RecipeRepos/com.github.autopkg.MLBZ521-recipes/CrowdStrike Falcon/CrowdStrikeURLProvider.py", line 174, in main
    download_url = f"{api_region_url}/sensors/entities/download-installer/v1?id={sha256}"
UnboundLocalError: local variable 'sha256' referenced before assignment
```

**Comment by MLBZ521** [comment]
Hello @K3ll3r, sorry for the delayed response.  Were you able to track this down?  I haven't been seeing any issues in my runs...

For the `sha256` variable to not be assigned, either a matching version was not found.  Currently, as the Processor is written, there isn't really any way to determine what's going on without editing it debug the issue.

**Comment by justN0fun** [comment]
@K3ll3r  In case this helps anyone else, I had the same issue. I updated to the latest CrowdStrike Falcon.download and I also had to update my POLICY_ID. The existing ID I had used in the past no longer existed in my CS account. Once I did both steps, I could run the download again

**Comment by Lotusshaney** [comment]
Trying this out and Im getting this problem downloading V7 versions

`Traceback (most recent call last):
  File "/Users/redacted/Library/AutoPkg/RecipeRepos/com.github.autopkg.MLBZ521-recipes/CrowdStrike Falcon/CrowdStrikeURLProvider.py", line 136, in main
    for policy in json_data["resources"]:
KeyError: 'resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Users/redacted/Library/AutoPkg/RecipeRepos/com.github.autopkg.MLBZ521-recipes/CrowdStrike Falcon/CrowdStrikeURLProvider.py", line 148, in main
    raise ProcessorError("Failed to match a Sensor Update Policy!")
autopkglib.ProcessorError: Failed to match a Sensor Update Policy!
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
Failed to match a Sensor Update Policy!
Failed.`

Any Ideas
